### ISSUE TITLE
求助~口袋房间投票消息播报失败

### ISSUE THREAD

**Issue by Lofalt** [chinshin/CQBot_hzx#12]
投票消息没有播报 CQBot.log 提示-WARNING-
local variable ‘msg’ referenced before assignment
不知道是哪里出了问题_(:з」∠)_ 
望解答~万分感谢o(╥﹏╥)o

**Comment by chinshin** [comment]
其他类型的口袋消息是否正常。


如果正常的话，我看了一下koudai.py的最后几行，def msg_ticket中，投票信息可能是被其他聚聚留言板信息刷下去了（因为代码逻辑只查询了第一页），或者是在判断逻辑中被忽略了。line320将早于一个查询周期前的消息忽略掉了，但我没有将msg在判断前初始化，造成了msg这个变量未定义就调用的错误。


所以问题应该是：被判断逻辑忽略掉了


解决方法：

考虑修改判断方法，比如多加几秒的延迟（不可以直接去掉，去掉的后果就是聚聚留言板第一页的投票信息只要存在就会在每个查询周期被播报出来，无论是否已经被播报过）


目前在xwy家和ggb家的试运行都暂时没问题，同时我会在下个版本修复这个报错问题。

**Comment by Lofalt** [comment]
谢谢解答！现在可以提取到信息了，但我刚才试着投了0.1票结果显示有未知格式的文字信息.. 是不是我这边的问题_(:з」∠)_

**Comment by chinshin** [comment]
那个不要紧。。。

因为你是用的自己的号。。。你投票（送礼物）那么mainpage（口袋房间主界面）上除了小偶像发的消息还会有你的礼物消息。。。我只排除了使用者自己说的话，忘了还有自己送的礼物信息。。。下个版本我一起加个识别然后忽略掉吧😂

**Comment by Lofalt** [comment]
我换了一个监控的号然后还是只会播报 有未知格式文字信息而不会播报投了0.1票T_T 不知道是什么问题_(:з」∠)_

**Comment by chinshin** [comment]
看一下log呢，这个未知类型文字消息会打到log的

**Comment by Lofalt** [comment]
2018-06-29 22:18:59,654 - INFO - 
有未知格式的文字消息

2018-06-29 22:18:59,654 - INFO - 
{'sourceId': '5771876', 'isSpecial': '0', 'giftPic': '/voteticket01.png', 'source': 'juju', 'chatType': 2, 'senderLevel': 'LV1', 'fromApp': 2, 'messageObject': 'jujuLive', 'contentType': 3, 'senderId': 382604, 'senderRole': 0, 'content': '投出了0.1票', 'giftCount': 1, 'senderName': 'Lofalt', 'senderAvatar': '/mediasource/avatar/20180629/153028062945660RKqVuQr0.png', 'platform': 'android', 'giftName': '0.1票', 'giftId': 'voteticket01', 'text': '投出了0.1票', 'senderHonor': ';'}

这样_(:з」∠)_

**Comment by chinshin** [comment]
你这就是自己的号投的票在mainpage上显示，然后被抓取到了当做小偶像的消息被播报。。。投票也算是礼物类型。。。


你改完代码和setting.conf后，还要吧setting.conf中的token的值删掉，tonen对应的还是你原来的账号信息；然后重跑脚本，一个周期后会自动获取新账号的token。


至于为什么没被播报，应该是你原来的号的礼物信息不会显示在原来的聚聚留言板上。

**Comment by chinshin** [comment]
我试了一下，自己的号投的票（或者礼物）不会出现在自己账号对应的聚聚留言板上，所以抓取不到😂

**Comment by Lofalt** [comment]
明白了，谢谢大佬！终于搞定了，感动o(╥﹏╥)o 真的麻烦你了~
