### ISSUE TITLE
翻牌名字显示

### ISSUE THREAD

**Issue by flydsc** [chinshin/CQBot_hzx#14]
一点点心得分享一下。

普通翻牌返回的字段应该已经没有faipaiName这一项了，不过好在有faipaiUserID这一项，所以我测试了一下，可以用这个ID，通过口袋充值的接口获取到nickName，大概代码如下：
```python
def getRoom_nickname(nicknameID):
    url = 'http://zhibo.ckg48.com/Recharge/ajax_post_checkinfo'
    form = {
        "pocket_id": nicknameID
    }
    r = requests.post(url, data=form).json()
    return r
```
然后引用就很容易了，直接在原返回数据中引用即可
```python
nicknameID = extInfo["faipaiUserId"]
```

纯粹分享心得，希望能有帮助，感谢@chinshin的开源精神。

**Comment by chinshin** [comment]
谢谢聚聚分享

**Comment by chinshin** [comment]
再次感谢聚聚分享，同时已对`koudai48.py`做出[更新](https://github.com/chinshin/CQBot_hzx#更新记录)。

**Comment by flydsc** [comment]
CKG48整体下线，导致API整体变更，名字的api已经换成

https://live.48.cn/Recharge/ajax_post_checkinfo
