### ISSUE TITLE
增加对酷Q版本识别，用pro的可以直接发送语音和图片

### ISSUE THREAD

**Issue by chinshin** [chinshin/CQBot_hzx#2]

**Comment by a19880730** [comment]
您好，关键词回复不太好用，请求支持

**Comment by chinshin** [comment]
@a19880730 group.py跑起来了吗；还有看一下酷q的日志（debug）

**Comment by a19880730** [comment]
能加我qq么，200839006，方便联系，谢谢啦




在 2018-02-21 22:38:15，"ChenZhen" <notifications@github.com> 写道：


@a19880730 group.py跑起来了吗；还有看一下酷q的日志（debug）

**Comment by a19880730** [comment]
group.py跑起来了，是先运行的group.py，然后启动的main.py。
现在集资可以正常播报，就是关键词回复不行，麻烦您方便的话加我qq：200839006，谢谢啦





在 2018-02-21 22:38:15，"ChenZhen" <notifications@github.com> 写道：


@a19880730 group.py跑起来了吗；还有看一下酷q的日志（debug）

**Comment by chinshin** [comment]
实现了
