### ISSUE TITLE
Roomid 和 owner id 如何找到？

### ISSUE THREAD

**Issue by Heheda48** [chinshin/CQBot_hzx#21]

**Comment by chinshin** [comment]
https://github.com/chinshin/CQBot_hzx/blob/master/searchMember.py
用这个查询

**Comment by Heheda48** [comment]
用searchMember查询时出现connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))错误

**Comment by Heheda48** [comment]
已解决，感谢
