### ISSUE TITLE
请问运行main.py时报错是为什么Traceback (most recent call last)

### ISSUE THREAD

**Issue by halfofcola** [chinshin/CQBot_hzx#27]
**具体报错内容：**
D:\Python\Python37\python.exe F:/Download/CQBot_hzx-master/CQBot_hzx-master/main.py
Traceback (most recent call last):
  File "F:/Download/CQBot_hzx-master/CQBot_hzx-master/main.py", line 26, in <module>
    interval_md = md_interval()
  File "F:\Download\CQBot_hzx-master\CQBot_hzx-master\setting.py", line 79, in md_interval
    cf.readfp(cfgfile)
  File "D:\Python\Python37\lib\configparser.py", line 762, in readfp
    self.read_file(fp, source=filename)
  File "D:\Python\Python37\lib\configparser.py", line 717, in read_file
    self._read(f, source)
  File "D:\Python\Python37\lib\configparser.py", line 1079, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'F:\\Download\\CQBot_hzx-master\\CQBot_hzx-master\\setting.conf', line: 1
'\ufeff[idol]\n'

Process finished with exit code 1

**Comment by IcyBiscuit** [comment]
可能是文件编码格式问题
请问用的是什么文本编辑器编辑配置文件的呢？
可以检查一下`CQBot_hzx-master\setting.conf`文件的编码格式是否为`UTF-8`（不带BOM）

**Comment by chinshin** [comment]
你是不是用记事本打开过了，记事本呵word会在文件头加个东西。

建议使用notepad++编辑文件。

**Comment by halfofcola** [comment]
> 可能是文件编码格式问题
> 请问用的是什么文本编辑器编辑配置文件的呢？
> 可以检查一下`CQBot_hzx-master\setting.conf`文件的编码格式是否为`UTF-8`（不带BOM）
> <img alt="image" width="257" src="https://user-images.githubusercontent.com/18629757/59513404-6090b380-8eed-11e9-8ccc-3cc8347e7c90.png">

我用记事本打开了，怪不得会这样，现在已经弄好了~感谢回答！

**Comment by halfofcola** [comment]
> 你是不是用记事本打开过了，记事本呵word会在文件头加个东西。
> 
> 建议使用notepad++编辑文件。

感谢告知！确实是记事本的问题~对了新版更新据说增加了投票播报，请问这个功能在哪里开启呢~还有每次修改完配置文件是不是都要重新启动cool q 才可以运行？ 抱歉 我的问题有点多。。

**Comment by chinshin** [comment]
投票播报默认就是开启的，在koudai48.py里面有改动。

改完配置文件不需要重启酷q，只需要把运行的py脚本关掉重运行就行。

**Comment by halfofcola** [comment]
> 投票播报默认就是开启的，在koudai48.py里面有改动。
> 
> 改完配置文件不需要重启酷q，只需要把运行的py脚本关掉重运行就行。

好的，十分感谢！！
