### ISSUE TITLE
上报地址无法访问

### ISSUE THREAD

**Issue by Nothatcold07** [chinshin/CQBot_hzx#35]
[大佬你好，我第一次接触这个 设置的时候 coolQ给我反馈
2020-06-04 22:55:01.244] [I] [日志] 日志控制台开启成功
[2020-06-04 22:55:01.252] [I] [HTTP] 开启 HTTP 服务器成功，开始监听 http://0.0.0.0:5700
[2020-06-04 22:55:03.471] [W] [HTTP] HTTP 上报地址 http://127.0.0.1:8080/ 无法访问
[2020-06-04 22:55:46.171] [W] [HTTP] HTTP 上报地址 http://127.0.0.1:8080/ 无法访问

然后还有 
setting里 口袋48那一项 
msgTime = 0
这个设置是正确的嘛

**Comment by Nothatcold07** [comment]
> > [2020-06-04 22:55:03.471] [W] [HTTP] HTTP 上报地址 http://127.0.0.1:8080/ 无法访问
> > [2020-06-04 22:55:46.171] [W] [HTTP] HTTP 上报地址 http://127.0.0.1:8080/ 无法访问
> 
> 看看`group.py`是不是没跑起来，不过这个和口袋48无关，可以忽略。
> 
> > setting里 口袋48那一项
> > msgTime = 0
> > 这个设置是正确的嘛
> 
> 是正确的

1080无法上报的问题解决了 
但是还是不行
然后我的group.py运行得一直是
* Serving Flask app "cqhttp" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
是不是设置还是有问题啊

**Comment by chinshin** [comment]
这样就是正确的了，不过如果你对qq群消息不需要什么处理，其实无需运行`group.py`
