### ISSUE TITLE
微博接口问题

### ISSUE THREAD

**Issue by AbnerLiu** [chinshin/CQBot_hzx#4]
https://m.weibo.cn/api/container/getIndex?containerid=xxxxx
这个接口返回数据是不是变了，我看返回的json，response['data']里面没有‘cards’这个key ，获取不到微博

**Comment by AbnerLiu** [comment]
是我的containerid填错了吗，我用你的代码的接口地址可以获取到，改成
https://m.weibo.cn/api/container/getIndex?containerid=1005055885940120
这个就没有了

**Comment by chinshin** [comment]
是你的 containerid 填错了

m.weibo.cn/p/***是会返回两个 XHR 的，一个是账户信息，一个才是需要抓取的微博 index

你填的 containerid 是对应账户信息界面的

tlj 微博的 containerid 应该是 `https://m.weibo.cn/api/container/getIndex?containerid=1076035885940120`

**Comment by AbnerLiu** [comment]
非常感谢
