### ISSUE TITLE
摩点逻辑改进

### ISSUE THREAD

**Issue by chinshin** [chinshin/CQBot_hzx#5]
1. 摩点已知 bug：吐空单、吐错单、返回订单总额延迟+数值偏差；

2. 逻辑拟修改为：
和口袋48逻辑一致，定义全局变量，储存最新订单时间；

3. 一个思路：
未来所有订单写入 CSV或引入轻量级 db；

**Comment by flydsc** [comment]
可以用SQLlite试试看？其实也就是写入文件，这样服务器的负担也不重，可以实现很多新功能，例如日排名之类的
