### ISSUE TITLE
微博接口的ID搞不懂。。

### ISSUE THREAD

**Issue by Lofalt** [chinshin/CQBot_hzx#7]
[weibo]
weiboid = 1076036034210438
weibourl = https://m.weibo.cn/api/container/getIndex?containerid=1076036034210438
interval = 60

微博的ID是这样填吗~ 我拿自己的微博号试了好多次都不行 不知道是什么原因T_T 
望解答T_T

**Comment by chinshin** [comment]
是这样填

**Comment by Lofalt** [comment]
我拿自己的号试了好多遍都没有反应_(:з」∠)_ 口袋和摩点的监控都没有问题

**Comment by chinshin** [comment]
1. 微博初始化在一个interval时间后。过一个interval再发新微博试试；

2.查看一下自己微博的containerid是否正确

**Comment by Lofalt** [comment]
还是不行.._(:з」∠)_ 
这是我的微博地址 http://weibo.com/u/2563573114
然后我是这样填的 
[weibo]
weiboid = 1076032563573114
weibourl = https://m.weibo.cn/api/container/getIndex?containerid=1076032563573114
interval = 60
我隔了一分多钟再发还是没有反应_(:з」∠)_

**Comment by chinshin** [comment]
..(:з」∠) id对的呀

看下log呢

**Comment by Lofalt** [comment]
是这个吗_(¦3」∠)_

**Comment by chinshin** [comment]
吧 `main.py`里的line93 改成`WARN(e)`，看看具体报错

**Comment by Lofalt** [comment]
2018-03-25 20:59:26,371 - WARNING - list index out of range

**Comment by chinshin** [comment]
我知道了，应该是我之前一次更新改错了list的获取范围


尝试解决办法：修改`weibo.py` line 111 为 `for i in range(0, 4):`

**Comment by Lofalt** [comment]
解决啦！谢谢聚聚！！！

**Comment by hmxgg** [comment]
不好意思，才看到邮件


发自网易邮箱大师
在2018年3月25日 21:03，ChenZhen<notifications@github.com> 写道：

我知道了，应该是我之前一次更新改错了list的获取范围

尝试解决办法：修改weibo.py line 111 为 for i in range(0, 4):
