### ISSUE TITLE
apscheduler 调度警告

### ISSUE THREAD

**Issue by flydsc** [chinshin/CQBot_hzx#9]
代码main.py在运行一段时间之后会提示skipped: maximum number of running instances reached

我猜应该是摩点请求延迟过高？

是不是考虑把max_instances调高一些呢？

**Comment by chinshin** [comment]
可能是，暂时提高了实例数，增加了任务合并等参数，已作出[修改](https://github.com/chinshin/CQBot_hzx/blob/7092b6555a04eda4a629dfca0b8f30339e4195fa/main.py#L132)
